[project]
name = "etl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sreeshanth", email = "sreeshanthkprakash@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.3.0",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "psycopg2-binary>=2.9.13",
]

[project.scripts]
etl = "etl:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
